choco install adb -y
choco install autohotkey.portable -y
choco install blender -y
choco install chocolatey -y
choco install chocolatey-compatibility.extension -y
choco install chocolatey-core.extension -y
choco install chocolatey-dotnetfx.extension -y
choco install chocolatey-misc-helpers.extension -y
choco install chocolatey-windowsupdate.extension -y
choco install composer -y
choco install cpu-z -y
choco install cpu-z.install -y
choco install darktable -y
choco install dotnet4.7.1 -y
choco install dotnet-6.0-desktopruntime -y
choco install dotnet-7.0-desktopruntime -y
choco install dotnet-desktopruntime -y
choco install dotnetfx -y
choco install etcher -y
choco install freecad -y
choco install handbrake -y
choco install handbrake.install -y
choco install hwmonitor -y
choco install KB2919355 -y
choco install KB2919442 -y
choco install KB2999226 -y
choco install KB3033929 -y
choco install KB3035131 -y
choco install KB3063858 -y
choco install kicad -y
choco install kodi -y
choco install libreoffice -y
choco install libreoffice-fresh -y
choco install mkcert -y
choco install obs -y
choco install obs-studio -y
choco install obs-studio.install -y
choco install pack -y
choco install palemoon -y
choco install php -y
choco install powertoys -y
choco install python -y
choco install python3 -y
choco install python311 -y
choco install qbittorrent -y
choco install rufus -y
choco install sabnzbd -y
choco install sourcetree -y
choco install speedfan -y
choco install vagrant -y
choco install vcredist140 -y
choco install vcredist2008 -y
choco install vcredist2015 -y
choco install vcredist2017 -y
choco install vcxsrv -y
choco install windirstat -y
choco install winfsp -y
choco install winscp -y
choco install winscp.install -y
